# Generated by Django 3.1.5 on 2022-01-09 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_program', '0002_auto_20220109_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_abbreviations',
            new_name='class_code',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_abbreviations',
            new_name='program_code',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_updated_at', models.DateTimeField(auto_now=True)),
                ('topic_created_at', models.DateTimeField(auto_now_add=True)),
                ('topic_code', models.TextField(blank=True, max_length=250, null=True)),
                ('topic_name', models.TextField(blank=True, max_length=250, null=True)),
                ('topic_detail', models.TextField(blank=True, max_length=500, null=True)),
                ('topic_status', models.BooleanField(blank=True, default=True, null=True)),
                ('topic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic_class', to='study_program.class')),
                ('topic_user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic_user_created', to=settings.AUTH_USER_MODEL)),
                ('topic_user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
