# Generated by Django 3.1.5 on 2022-01-09 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_program', '0003_auto_20220109_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_url', models.TextField(blank=True, max_length=500, null=True)),
                ('lesson_view', models.TextField(blank=True, max_length=10, null=True)),
                ('lesson_code', models.TextField(blank=True, max_length=250, null=True)),
                ('lesson_name', models.TextField(blank=True, max_length=250, null=True)),
                ('lesson_detail', models.TextField(blank=True, max_length=500, null=True)),
                ('lesson_status', models.BooleanField(blank=True, default=True, null=True)),
                ('lesson_evaluate', models.TextField(blank=True, max_length=10, null=True)),
                ('lesson_download', models.TextField(blank=True, max_length=200, null=True)),
                ('lesson_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lesson_topic', to='study_program.topic')),
                ('lesson_user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lesson_user_created', to=settings.AUTH_USER_MODEL)),
                ('lesson_user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lesson_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
