# Generated by Django 3.1.5 on 2022-01-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_files',
            field=models.FileField(default=1, upload_to='lesson/'),
            preserve_default=False,
        ),
    ]
