# Generated by Django 3.1.5 on 2022-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_program', '0005_lesson_lesson_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_files',
            field=models.FileField(upload_to='media/lesson/'),
        ),
    ]
