# Generated by Django 3.1.5 on 2022-07-24 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_description', models.TextField(blank=True, max_length=500, null=True)),
                ('about_enable', models.BooleanField(blank=True, default=True, null=True)),
                ('about_status', models.BooleanField(blank=True, default=True, null=True)),
                ('about_created_at', models.DateTimeField(auto_now_add=True)),
                ('about_updated_at', models.DateTimeField(auto_now=True)),
                ('about_user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_user_created', to=settings.AUTH_USER_MODEL)),
                ('about_user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
